config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :hostels



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hostel.rb
class Hostel < ApplicationRecord
  belongs_to :owner, class_name: 'User'

  validates :name, :address, :capacity, :type_pets, :description, presence: true

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :hostel
  validates :date_departure, :date_of_arrival, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :hostels, foreign_key: 'owner_id', dependent: :destroy
  #has_many :reservations, dependent: :destroy

  validates :first_name, :name, :address, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hostels_controller.rb
class HostelsController < ApplicationController
  def index
    @hostels = Hostel.all
  end

  def show
    @hostel = Hostel.find(params[:id])
  end

  def new
    @hostel = Hostel.new
  end

  def create
    @hostel = Hostel.create(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @hostels = Hostel.first(2)
    if params[:reservation]
      redirect_to root_path, notice: 'Votre réservation a bien été enregistrée'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hostels/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-8">
      <div class="cards">
        <% @hostels.each do |hostel| %>
          <%= link_to hostel_path(hostel) do %>
            <div class="card-product">
              <%= image_tag hostel.image_url %>
              <h1><%= hostel.name %></h1>
              <h2><%= hostel.address %></h2>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/hostels/show.html.erb
<div class=container>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))">
    <div class="container">
      <h1>Detail of hostel</h1>
    </div>
  </div>
  <br>
  <br>
  <div class="card-trip">
    <div class="col-12 sm-8 offset-4">
      <img src= <%= @hostel.image_url %> >
      <div class="card-trip-infos">
        <div>
          <h2><%=@hostel.name %></h2>
          <p><%= @hostel.address %></p>
          <p><%= @hostel.capacity %></p>
          <p><%= @hostel.type_pets %></p>
          <p><%= @hostel.description %></p>
          <%= link_to "reserver", root_path(reservation: true), class: "btn btn-ghost", notice: 'Votre réservation a bien été enregistrée' %>
        </div>
        </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrenteMillionsDAmis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://thumbs.dreamstime.com/b/groupe-d-animaux-familiers-23828640.jpg);">
  <div class="container">
    <h1>30 millions d'amis</h1>
    <p>SOYEZ TRANQUILLE !<br>La solution à votre problème</p>
    <%= link_to "decouvrez plus", hostels_path, class:"btn btn-flat"  %>
  </div>
</div>

<div class="container mt-5">
  <div class="col-12 col-8">
    <div class="cards">
      <% @hostels.each do |hostel| %>
        <%= link_to hostel_path(hostel) do %>
          <div class="card-product">
            <%= image_tag hostel.image_url %>
            <h1><%= hostel.name %></h1>
            <h2><%= hostel.address %></h2>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>